### ISSUE TITLE
Seldon CRD fails to deploy on OpenShift 4.3

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/manifests#14]
OpenShift 4.3 comes with an update to Kubernetes 1.16 which results in some incompatibilities - this time for Seldon CRD to fail to be applied.

It is already known to Kubeflow community - https://github.com/kubeflow/manifests/issues/375

@cliveseldon I see your changes in upstream basically resolve to replacing the resources with new version in master, what would you suggest to do here as we would like to keep 0.7 working on OCP 4.3 (i.e. k8s 1.16)?

**Comment by cliveseldon** [comment]
Are you suggesting updating kubeflow 0.7 to allow it to be installed on 4.3 including Seldon?
Otherwise, could it be updated  to kubeflow 1.0 when its released.
Also, for Seldon could we update to 1.0.1 version of Seldon which should work on 1.16?

**Comment by vpavlin** [comment]
> Are you suggesting updating kubeflow 0.7 to allow it to be installed on 4.3 including Seldon?

That is my preferred short term fix now - we just published blog post and are adding docs to KF website on "How to run Kubeflow **0.7** on OpenShift **4.2**", but since new clusters will mostly be deployed with 4.3, we might get a lot of people hitting this issue, so fixing this in 0.7 (even if we do it here - in ODH fork) would be great

> Otherwise, could it be updated to kubeflow 1.0 when its released.

That is surely goal, but will take time

> Also, for Seldon could we update to 1.0.1 version of Seldon which should work on 1.16?

This might be actually the easiest thing to do here - simply cherrypick latest seldon from KF master (which is 1.0.1 if I am not mistaken), but I wanted to consult with you before we start breaking things:)

**Comment by cliveseldon** [comment]
If you can try cherrypicking it that would be great.

**Comment by cliveseldon** [comment]
Great. Glad its all working.
