### ISSUE TITLE
Plan to upgrade to kubeflow 1.0/1.1?

### ISSUE THREAD

**Issue by eterna2** [opendatahub-io/manifests#19]
Hi, are there any plans to resync with Kubeflow main repo and update to 1.0/1.1?

Because my org is planning to try out kubeflow. However, we have an existing OpenShift cluster on AWS. We are considering between spinning up an EKS and use AWS's variant of Kubeflow, vs the effort needed to update this repo to kf1.0 but saves on maintaining another k8s cluster (and also for further plans of moving to a production openshift cluster)?

Any opinions? I am not very familiar with openshift. Would be glad if someone can point to me the main diff for kubeflow in openshift vs k8s? So that I can better evaluate my options? (i.e. what are the key things I might need to change to make it work in openshift?)

I am a contributor to kubeflow and familiar how kf works in a typical kubernetes (i.e. EKS, AKS, ELK, etc. but not familiar with Openshift).

**Comment by nakfour** [comment]
Hi @eterna2 yes we are planning to upgrade to 1.0/1.1. For more information on our work to get KF running on OCP, please check this blog https://developers.redhat.com/blog/2020/02/10/installing-kubeflow-v0-7-on-openshift-4-2/

**Comment by eterna2** [comment]
Cool. I am new to openshift. Currently installing CRC on my machine. 

Do we have a branch for 1.0, so I can pull and try? 

I can probably contribute if we decided to go with the openshift variant of kubeflow.

**Comment by tks-ai** [comment]
i am facing a similar question.
it seems that the default branch is set to "v1.0-branch-openshift" a couple of days ago.
so is that means the kubeflow 1.0 is ready for openshift 4.x?

**Comment by nakfour** [comment]
@tks-ai yes that means if you install ODH 0.7 operator you can install KF 1.0, or manually from that branch
