### ISSUE TITLE
No permissions to list/create notebooks

### ISSUE THREAD

**Issue by crobby** [opendatahub-io/manifests#22]
When I navigate from the central dashboard to try to spawn a notebook (in a profile that was created by kubeflow), I get error messages on the Jupyter launch screen about no permissions to list notebooks and then trying to create a notebook also fails with a similar "no permission to create" message.
Error text is:  "User None is not authorized to list kubeflow.org.v1alpha1.poddefaults for namespace: mytestnamespace"

**Comment by crobby** [comment]
https://github.com/kubeflow/kubeflow/issues/4731

**Comment by crobby** [comment]
I poked at this a bit more.  I can see the following message in the Jupyter web app pod logs:

2020-04-20 20:09:43,391 | kubeflow_jupyter.common.auth | WARNING | No user credentials were found! Make sure you have correctly set the USERID_HEADER in the Jupyter Web App's deployment.

There are kustomize params available to set USERID_HEADER (and USERID_PREFIX) in the jupyter component as well as the central dashboard component, but I'm not sure what we'd set them to or if that is the right way to go about solving this.

**Comment by Manvi07** [comment]
Same issue with Kubeflow version 1.0.2. Unable to use the Jupyter Notebook Service on Kubeflow

**Comment by crobby** [comment]
> Same issue with Kubeflow version 1.0.2. Unable to use the Jupyter Notebook Service on Kubeflow

The 1.0-branch-openshift should now contain manifests that get around this issue for kubeflow 1.0 on Openshift.  I think we pushed the fix just last week.
