### ISSUE TITLE
KF 1.0 istio cluster-local-gateway crashes

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/manifests#29]
We need to add cluster-local-gateway to our kfctl-openshift manifest to enable internal routing that is needed by knative

**Comment by nakfour** [comment]
Fixed in #30

**Comment by adrian555** [comment]
@nakfour If I want to add `cluster-local-gateway` as part of the Kubeflow, which `namespace` should it be installed in? Looking at the examples https://github.com/opendatahub-io/manifests/blob/v1.0-branch-openshift/kfdef/kfctl_gcp_iap.v1.0.2.yaml#L26 and https://github.com/opendatahub-io/manifests/blob/v1.0-branch-openshift/kfdef/kfctl_ibm.v1.0.2.yaml#L25, they all seem to install in the `istio-system` namespace. Is this also applied for the openshift?

**Comment by nakfour** [comment]
@adrian555 we have not installed "cluster-local-gateway" in our openshift kfctl file yet, but I see that it should be in "istio-system" namespace. I will keep this issue open since we need to install this to get Knative working. If you add it and it works on OCP please send us a PR
