### ISSUE TITLE
Jupyter Notebooks KF 1.0

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/manifests#31]

**Comment by crobby** [comment]
Here's what I've found so far:
1)  Something is seriously wrong with auth/noauth.  If you go to the JH UI, you will quickly start seeing error messages like "User None can't list/create pvc/notebooks in namespace <whatever>".  The "None" part of the equation can be solved by forcing a header to be added that can be set to whatever (anonymous@kubeflow.org is the default), but that only serves to succeed in getting the error messages to say that "anonymous@kubeflow.org can't do [verb] on namespace <whatever>".  I'm pretty lost on where to proceed on this issue.

2)  The notebook controller on the 1.0 branch is still pointing at our 0.7 image.  In theory, we'd be able to use upstream now that my ADD_FSGROUP patch made it upstream, but sadly, it didn't make it in to the 1.0 branch/release (it is in for 1.1 and future though), so I will submit a PR that will point at our new custom image (1.0 + my ADD_FSGROUP patch) and it will also include the ENV var to make it behave correctly at runtime.
