### ISSUE TITLE
KF 1.0 Katib

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/manifests#36]

**Comment by nakfour** [comment]
@panbalag please review

**Comment by vpavlin** [comment]
Upstream PR: https://github.com/kubeflow/manifests/issues/1323

**Comment by vpavlin** [comment]
Another upstream PR to fix examples: https://github.com/kubeflow/katib/pull/1241

**Comment by vpavlin** [comment]
I am going to mark this as DONE - the Katib works for us and there are bunch of upstream PRs which I'll keep track of
