### ISSUE TITLE
SPIKE Investigate ODH + KF 1.0 Kubeflow mixing

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/manifests#37]
- [x] Verify TF Job 
- [x] Create additional KFDef
- [x] Create a documentation PR for odh.io
- [ ]  Verify Pytorch

**Comment by nakfour** [comment]
KF tfjob pytorch can install with ODH.

**Comment by vpavlin** [comment]
I have verified TF Job and submitted PRs...

I believe there will have to be additional PR for Pytorch since I fixed the upstream, but did not update the image in our manifests, so I will close this one and create a follow up PR for Pytorch to unblock the 0.7 release
