### ISSUE TITLE
Question: Multi-user, auth-enabled support?

### ISSUE THREAD

**Issue by rdejana** [opendatahub-io/manifests#59]
Working through running Kubeflow on OpenShift and so far so good, but I have a question, is multi-user with auth-enabled supported when running in OpenShift?  Thanks, Ryan.

**Comment by nakfour** [comment]
@rdejana Kubeflow does support multi-user options for some components such as Notebooks. However not all components have added this support yet. Also there is no official support for a specific auth-enabled method, even though some contributors have submitted example kfdefs with auth enabled. If you have any recommendation/suggestions please open them as enhancements or feature requests.
