### ISSUE TITLE
kfctl_openshift.yaml services not create and routed

### ISSUE THREAD

**Issue by ticlazau** [opendatahub-io/manifests#60]
Hello,

I have deployed successfully 
https://github.com/opendatahub-io/manifests/blob/v1.0-branch-openshift/kfdef/kfctl_openshift.yaml
on OpenShift 4.4.20, but none of the associated routes have been created (ie. centraldashboard, katib-ui etc)

Has anyone the same issue with this yam file?

Rgds,
FM

**Comment by nakfour** [comment]
@ticlazau can you see the istio-ingress route in the istio-system namespace? This is the route to the KF portal.

**Comment by ticlazau** [comment]
@nakfour I have it but is in the istio-system namespace not in kubeflow (see attached)
<img width="1333" alt="Screenshot 2020-10-17 at 01 30 34" src="https://user-images.githubusercontent.com/30878420/96322252-9e897480-1018-11eb-91e7-6ef960ade857.png">
In addition,

**Comment by nakfour** [comment]
What happens when you click on the ingress route?

**Comment by ticlazau** [comment]
Is going to the KubeFlow setup page where I am requested to install into a namespace.

**Comment by nakfour** [comment]
Yes this is the correct behavior, you need to enter a valid namespace name where some of the KF component such as Jupyter Notebook servers will run.
