### ISSUE TITLE
Question: is there a working Kubeflow 1.0 kfdef for ServiceMesh?

### ISSUE THREAD

**Issue by adrian555** [opendatahub-io/manifests#62]
I am looking at this kfdef https://github.com/opendatahub-io/manifests/blob/v1.0-branch-openshift/kfdef/kfctl_openshift_servicemesh.yaml, but apparently this does not work as it misses memberroll application as well as no servicemesh overlay in istio/istio. Also the istio release installed through the service mesh now in OCP already has the clusterrbacconfig deprecated.

So is there a working version of kfdef that actually supports running kubeflow 1.0 with the istio installed through service mesh operator from OCP?

Thanks.

cc @animeshsingh

**Comment by nakfour** [comment]
@adrian555 at this time we have not tested SM with KF 1.0
