### ISSUE TITLE
Kubectl apply doesn't work with several CRDs in Kubeflow

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/manifests#87]
Kubeflow applications are successfully created when deployed through Open Data Hub Operator. However, several CRDs failed on update. This results in failed reconciliation. 

CRDs of the following components fail to update:
- Cert-manager 1.5
- Knative
- Training Operator

This failure is observed after moving to v1 of API `customresourcedefinition.apiextensions.k8s.io` .

**Comment by tks-ai** [comment]
the same here ,the Open Data Hub Operator will hang up while update these CRDs.
Is there any solution??

**Comment by VaishnaviHire** [comment]
@tks-ai https://github.com/opendatahub-io/opendatahub-operator/pull/171 fixes this issue

**Comment by VaishnaviHire** [comment]
Fixed. The change will be available for the next ODH release
