### ISSUE TITLE
May some of the paths no longer available

### ISSUE THREAD

**Issue by tks-ai** [opendatahub-io/manifests#97]
The recent update of servicemesh made changes to paths,but it seems this kfdef still points to the old paths.
Is there a plan to update?

https://github.com/opendatahub-io/manifests/blob/a1286a179e672030daad3ac1026c19683a9c132e/openshift/kfdef/kfctl_openshift_v1.5.0_odh.yaml

**Comment by strangiato** [comment]
When applying the kfdef linked by @tks-ai I am getting the following error message in the operator:

```
level=error msg="Error evaluating kustomization manifest for openshift-scc: accumulating resources: couldn't make target for path '../../.cache/manifests/manifests-1.5-branch-openshift/openshift/openshiftstack/application/openshift/openshift-scc': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kubeflow/kubeflow/.cache/manifests/manifests-1.5-branch-openshift/openshift/openshiftstack/application/openshift/openshift-scc'"
```

It appears that the openshift-scc component should point here instead:

```
openshift/openshiftstack/application/openshift/openshift-scc/overlays/istio
```
